### ISSUE TITLE
Boost Progress

### ISSUE THREAD

**Issue by r-barnes** [boostorg/timer#12]
[boost/progress.hpp](https://www.boost.org/doc/libs/1_71_0/boost/progress.hpp) warns me:

    include/boost/timer.hpp:21:98: note: #pragma message: This header is deprecated. 
    Use the facilities in <boost/timer/timer.hpp> instead.
    BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp>" )

But when I look in [boost/timer.hpp](https://www.boost.org/doc/libs/1_71_0/boost/timer/timer.hpp) there's no obvious path to upgrade, since there is no `boost::progress_display` class.

How am I intended to deal with the deprecation of `progress.hpp`, other than rewriting it?

**Comment by pdimov** [comment]
Fair point. I added the deprecation message because the old timers have been explicitly marked as deprecated in the documentation for a long while (since Boost 1.53, https://www.boost.org/doc/libs/1_53_0/libs/timer/doc/index.html.)

But it's true that `progress_display` has no "modern" equivalent.

I'm not sure what's the best way to handle this; add `boost::timer::progress_display` with the same contents as the deprecated one?

**Comment by glenfe** [comment]
Adding `boost::timer::progress_display` in a new header, <boost/timer/progress_display.hpp>. With the same contents is fine. I don't think we're using it in other Boost libraries, and users are probably already aware that it won't receive updates (though contributions wouldn't be turned away).

**Comment by r-barnes** [comment]
This seems reasonable to me.

**Comment by r-barnes** [comment]
Should I make a PR?

**Comment by pdimov** [comment]
No need, thanks. See https://github.com/boostorg/timer/commit/c221a60102ed618a82116f84407de3f1713aa10f.
